practice_1/case3/app/app/urls.py
#from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("notes.urls")),
    #path("admin/", admin.site.urls),
]

practice_1/case3/app/notes/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("features/", views.features, name="features"),
    path("contacts/", views.contacts, name="contacts"),


    path('register/', views.register, name='register'),
    #path('login/', views.register, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('notes/create', views.note_create, name='note_create'),
    path('notes/view/<int:pk>/', views.note_view, name='note_view'),
    path('notes/remove/<int:pk>/', views.note_delete, name='note_delete'),
]

practice_1/case3/app/notes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.utils import timezone


class User(AbstractUser):
    pass

class Note(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

practice_1/case3/app/notes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Note

User = get_user_model()

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content']

practice_1/case3/app/notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegistrationForm
from django.views.generic import ListView
from .models import Note
from .models import Note
from .forms import NoteForm

def index(request):
    notes = []
    if request.user.is_authenticated:
        notes = Note.objects.filter(user=request.user)

    return render(request, 'index.html', {'notes': notes})

def features(request):
    return render(request, 'features.html')

def contacts(request):
    return render(request, 'contacts.html')

def login(request):
    return render(request, 'login.html')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = UserRegistrationForm()
    return render(request, 'register.html', {'form': form})


def note_create(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()

            return redirect('index')
    else:
        form = NoteForm()

    return render(request, 'notes/note_create.html', {'form': form})


def note_view(request, pk):
    note = get_object_or_404(Note, pk=pk, user=request.user)

    return render(request, 'notes/note_view.html', {'note': note})

def note_delete(request, pk):
    note = get_object_or_404(Note, pk=pk, user=request.user)
    note.delete()

    return redirect('index')

practice_1/case3/app/notes/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#712cf9">

    <title>{% block title %}Notes Service{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/cover.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <script src="{% static 'js/color-modes.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</head>
<body class="d-flex h-100 text-bg-dark">





<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">
                <a href="{% url 'index' %}" style="color:white; text-decoration: none;">Notes</a>
            </h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-0 {% if request.path == '/' %}active{% endif %}" href="{% url 'index' %}">Home</a>
                <a class="nav-link fw-bold py-1 px-0 {% if request.path == '/features/' %}active{% endif %}" href="{% url 'features' %}">Features</a>
                <a class="nav-link fw-bold py-1 px-0 {% if request.path == '/contacts/' %}active{% endif %}" href="{% url 'contacts' %}">Contact</a>

                {% if request.user.is_authenticated %}
                    <div class="">
                        <div class="dropdown">
                            <a class="nav-link fw-bold py-1 px-0 ms-5 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                    <path d="M8 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm4-2a4 4 0 0 0-4-4 4 4 0 0 0-4 4v1a4 4 0 0 0 1.556 3.18c.468.336.98.52 1.444.648a8.85 8.85 0 0 1 1.9.568 8.85 8.85 0 0 1 1.9-.568c.464-.128.976-.312 1.444-.648A4 4 0 0 0 12 7V6zm-4 5c-2.333 0-7 1.167-7 3.5v.5h14v-.5c0-2.333-4.667-3.5-7-3.5z"/>
                                </svg>
                                {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <a class="nav-link fw-bold py-1 px-0" href="{% url 'login' %}">Login</a>
                    <a class="nav-link fw-bold py-1 px-0" href="{% url 'register' %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </header>


    <main class="px-3">
        {% block content %}{% endblock %}
    </main>

    <footer class="mt-auto text-white-50 text-center">
        <p>Notes service, 2024. All rights reserved.</p>
    </footer>
</div>

</body>
</html>

practice_1/case3/app/notes/templates/contacts.html
<!-- templates/contacts.html -->
{% extends "base.html" %}

{% block title %}Contacts{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Contacts</h1>

        <p class="lead">Have questions or feedback? Feel free to reach out to us!</p>

        <a href="mailto:support@notes.com">support@notes.com</a>
    </div>
{% endblock %}

practice_1/case3/app/notes/templates/features.html
<!-- templates/features.html -->
{% extends "base.html" %}

{% block title %}Features{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Features of notes</h1>
        <p class="lead">
            Our Notes Service offers a range of features designed to help you manage your notes efficiently and effectively. Discover what makes our service unique and why it's the perfect choice for keeping your thoughts organized.
        </p>

        </br>

        <div class="list-group">
          <a href="#" class="list-group-item list-group-item-action">
            <strong>Easy to Use:</strong> Our intuitive interface makes it easy to create, edit, and organize your notes.
          </a>
          <a href="#" class="list-group-item list-group-item-action">
              <strong>Secure:</strong> Your notes are stored securely and can only be accessed by you.
          </a>
          <a href="#" class="list-group-item list-group-item-action">
              <strong>Accessible:</strong> Access your notes from any device, anytime, anywhere.
          </a>
          <a href="#" class="list-group-item list-group-item-action">
              <strong>Organized:</strong> Categorize your notes with tags and folders to keep everything in order.
          </a>
          <a href="#" class="list-group-item list-group-item-action">
              <strong>Searchable:</strong> Quickly find the notes you need with our powerful search functionality.
          </a>
          <a href="#" class="list-group-item list-group-item-action">
              <strong>Shareable:</strong> Share your notes with others easily and collaborate in real-time.
          </a>
        </div>
    </div>
{% endblock %}

practice_1/case3/app/notes/templates/index.html
<!-- templates/index.html -->
{% extends "base.html" %}

{% block title %}Welcome to Notes{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h2 class="mb-4">Your notes</h2>
                {% if notes %}
                    <div class="list-group">
                        {% for note in notes %}
                            <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                <a href="{% url 'note_view' note.pk %}" class="flex-grow-1" style="text-decoration: none; color: inherit;">
                                    {{ note.title }}
                                </a>
                                <form action="{% url 'note_delete' note.pk %}" method="post" class="mb-0">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure you want to delete this note?')">Delete</button>
                                </form>
                            </div>
                        {% endfor %}
                    </div>

                {% else %}
                    <p>No notes found.</p>
                {% endif %}
                <div class="w-100">
                    <a href="{% url 'note_create' %}" class="btn btn-primary mt-3 w-100">Add New Note</a>
                </div>
            </div>
        </div>
    {% else %}
        <div class="text-center">
            <h1>Welcome to Notes</h1>
            <p class="lead">
                A simple and effective service for managing your notes. Keep track of your thoughts, ideas, and important
                information all in one place. Start by registering or logging in to access your personal notes.
            </p>
            <p class="lead">
                <a href="{% url 'register' %}" class="btn btn-lg btn-light fw-bold border-white bg-white w-25">Register</a>
                <a href="{% url 'login' %}" class="btn btn-lg btn-primary w-25">
                    Login
                </a>
            </p>
        </div>
    {% endif %}




{% endblock %}

practice_1/case3/app/notes/templates/login.html
<!-- templates/login.html -->
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="row text-center">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Login</h2>
                    <form method="post">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="form-group">
                            {{ form.username.label_tag }}
                            {{ form.username }}
                            {% if form.username.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {% for error in form.username.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label_tag }}
                            {{ form.password }}
                            {% if form.password.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {% for error in form.password.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3 w-50">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

practice_1/case3/app/notes/templates/notes/note_create.html
<!-- templates/note_create.html -->
{% extends "base.html" %}

{% block title %}Create Note{% endblock %}

{% block content %}
    <style>
        #id_title {
            width: 100%;
        }

    </style>

    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Create Note</h2>
                    <form method="post">
                        {% csrf_token %}

                        {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Oops! Something went wrong.</strong> Please correct the errors below.
                                <ul>
                                    {% for field, errors in form.errors.items %}
                                        {% for error in errors %}
                                            <li>{{ field }}: {{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}

                        <div class="mb-3">
                            {{ form.title.label_tag }}<br/>
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            {{ form.content.label_tag }}
                            {{ form.content }}
                        </div>

                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Create Note</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

practice_1/case3/app/notes/templates/notes/note_view.html
<!-- templates/note_view.html -->
{% extends "base.html" %}

{% block title %}View Note{% endblock %}

{% block content %}
    <div class="row">
        <h1>{{ note.title }}</h1>
        <p>{{ note.content|linebreaksbr }}</p>

        <div class="mt-5 w-100">
            <p>Note created at: {{ note.created_at }}</p>
            <a href="{% url 'index' %}" class="btn btn-primary w-100">Back to Notes</a>
        </div>

    </div>
{% endblock %}

practice_1/case3/app/notes/templates/register.html
<!-- templates/register.html -->
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="row text-center">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Register</h2>
                    <form method="post">
                        {% csrf_token %}

                        {% if form.errors.items %}
                            <div class="alert alert-danger" role="alert">
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        {{field}}: {{ error }}
                                    {% endfor %}
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            {{ form.username.label_tag }}
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            {{ form.email.label_tag }}<br/>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            {{ form.password1.label_tag }}
                            {{ form.password1 }}
                        </div>
                        <div class="form-group">
                            {{ form.password2.label_tag }}
                            {{ form.password2 }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}